// Copyright (c) 2025, Qualcomm Innovation Center, Inc. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause

/**
* @addtogroup CGPAppClient
* @{
  Class CGPAppClient implements \link IGPAppClient \endlink interface.
  This service is exposed to HLOS client.
  This class should be used only by our GP stack, not by individual clients.
*/
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#define CGPAppClient_UID UINT32_C(0x199)

