// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

/** @cond */
interface IGPAppClient {
/** @endcond */

  /**
   * @addtogroup IGPAppClient
   * @{
   */

  /** @cond */
  /**
   * Error codes
   */
  error ERROR_INVALID_UUID_LEN;                /**< UUID length is invalid */
  error ERROR_APP_NOT_FOUND;                   /**< No loaded application with the requested UUID */
  error ERROR_APP_BLOCKED_ON_LISTENER;         /**< Deprecated, will not be returned */
  error ERROR_APP_UNLOADED;                    /**< App has been unloaded */
  error ERROR_APP_RESTART_FAILED;              /**< App restart failed */
  error ERROR_APP_AUTOLOAD_INVALID_BUFFER;     /**< Invalid buffer received during TA autoload */
  error ERROR_ACCESS_DENIED;                   /**< Client not allowed to access the TA*/
  /** @endcond */

  /**
    Opens a session with the trusted application.

    This method is part of the GP interface for the TA, and should not be directly used (internal to GP framework)

    The caller/implementer (depending on parameter type) manually marshals the
    content of four input/output buffers.

    @param[in]  uuid               TA to open a session with, as TEE_UUID.
    @param[in]  waitCBO            One waitCBO per session, will be used (when present) to implement the cancellation.
    @param[in]  cancelCode         Optional code to use for cancellations.
    @param[in]  connectionMethod   What CA identity credentials to use.
    @param[in]  connectionData     Optional connection group identifier.
    @param[in]  paramTypes         Parameter types, 1 byte per parameter.
    @param[in]  exParamTypes       Extended information for parameters, 1 byte per parameter.
    @param[in]  i1                 First input buffer.
    @param[in]  i2                 Second input buffer.
    @param[in]  i3                 Third input buffer.
    @param[in]  i4                 Fourth input buffer.
    @param[out] o1                 First output buffer.
    @param[out] o2                 Second output buffer.
    @param[out] o3                 Third output buffer.
    @param[out] o4                 Fourth output buffer.
    @param[in]  imem1              First optional memory region.
    @param[in]  imem2              Second optional memory region.
    @param[in]  imem3              Third optional memory region.
    @param[in]  imem4              Fourth optional memory region.
    @param[out] memrefOutSz1       Desired output size for memref 1, if larger than size provided.
    @param[out] memrefOutSz2       Desired output size for memref 2, if larger than size provided.
    @param[out] memrefOutSz3       Desired output size for memref 3, if larger than size provided.
    @param[out] memrefOutSz4       Desired output size for memref 4, if larger than size provided.
    @param[out] session            Newly opened session.
    @param[out] retValue           GP return value.
    @param[out] retOrigin          Where the GP return value originated.

    @return  Object_OK if successful.
   */
  method openSession(in buffer uuid,
                     in interface waitCBO,
                     in uint32 cancelCode,
                     in uint32 connectionMethod,
                     in uint32 connectionData,
                     in uint32 paramTypes,
                     in uint32 exParamTypes,
                     in buffer i1,
                     in buffer i2,
                     in buffer i3,
                     in buffer i4,
                     out buffer o1,
                     out buffer o2,
                     out buffer o3,
                     out buffer o4,
                     in interface imem1,
                     in interface imem2,
                     in interface imem3,
                     in interface imem4,
                     out uint32 memrefOutSz1,
                     out uint32 memrefOutSz2,
                     out uint32 memrefOutSz3,
                     out uint32 memrefOutSz4,
                     out interface session,
                     out uint32 retValue,
                     out uint32 retOrigin);

 /* Opens a session with the trusted application.

    This method is part of the GP interface for the TA, and should not be directly used (internal to GP framework)

    The caller/implementer (depending on parameter type) manually marshals the
    content of four input/output buffers.

    @param[in]  uuid               TA to open a session with, as TEE_UUID.
    @param[in]  waitCBO            One waitCBO per session, will be used (when present) to implement the cancellation.
    @param[in]  cancelCode         Optional code to use for cancellations.
    @param[in]  cancellationRequestTimeout Timeout for automatic request cancellation.
    @param[in]  connectionMethod   What CA identity credentials to use.
    @param[in]  connectionData     Optional connection group identifier.
    @param[in]  paramTypes         Parameter types, 1 byte per parameter.
    @param[in]  exParamTypes       Extended information for parameters, 1 byte per parameter.
    @param[in]  i1                 First input buffer.
    @param[in]  i2                 Second input buffer.
    @param[in]  i3                 Third input buffer.
    @param[in]  i4                 Fourth input buffer.
    @param[out] o1                 First output buffer.
    @param[out] o2                 Second output buffer.
    @param[out] o3                 Third output buffer.
    @param[out] o4                 Fourth output buffer.
    @param[in]  imem1              First optional memory region.
    @param[in]  imem2              Second optional memory region.
    @param[in]  imem3              Third optional memory region.
    @param[in]  imem4              Fourth optional memory region.
    @param[out] memrefOutSz1       Desired output size for memref 1, if larger than size provided.
    @param[out] memrefOutSz2       Desired output size for memref 2, if larger than size provided.
    @param[out] memrefOutSz3       Desired output size for memref 3, if larger than size provided.
    @param[out] memrefOutSz4       Desired output size for memref 4, if larger than size provided.
    @param[out] session            Newly opened session.
    @param[out] retValue           GP return value.
    @param[out] retOrigin          Where the GP return value originated.

    @return  Object_OK if successful.
   */
  method openSessionV2(in buffer uuid,
                       in interface waitCBO,
                       in uint32 cancelCode,
                       in uint32 cancellationRequestTimeout,
                       in uint32 connectionMethod,
                       in uint32 connectionData,
                       in uint32 paramTypes,
                       in uint32 exParamTypes,
                       in buffer i1,
                       in buffer i2,
                       in buffer i3,
                       in buffer i4,
                       out buffer o1,
                       out buffer o2,
                       out buffer o3,
                       out buffer o4,
                       in interface imem1,
                       in interface imem2,
                       in interface imem3,
                       in interface imem4,
                       out uint32 memrefOutSz1,
                       out uint32 memrefOutSz2,
                       out uint32 memrefOutSz3,
                       out uint32 memrefOutSz4,
                       out interface session,
                       out uint32 retValue,
                       out uint32 retOrigin);

  /** @} */ /* end_addtogroup IGPAppClient */
};

