// Copyright (c) 2025, Qualcomm Innovation Center, Inc. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause

/** @cond */
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"
#include "IWait.h"


#ifdef __clang__
#define __compiler_pragma_pre \
    _Pragma("clang diagnostic push") \
    _Pragma("clang diagnostic ignored \"-Wignored-attributes\"")
#define __compiler_pragma_post _Pragma("clang diagnostic pop")
#else
#define __compiler_pragma_pre
#define __compiler_pragma_post
#endif

#define IWait_DEFINE_INVOKE(func, prefix, type) \
    int32_t func(ObjectCxt h, ObjectOp op, ObjectArg *a, ObjectCounts k) \
    { \
        __compiler_pragma_pre \
         \
        __compiler_pragma_post \
        type me = (type) h; \
        switch (ObjectOp_methodID(op)) { \
            case Object_OP_release: { \
                if (k != ObjectCounts_pack(0, 0, 0, 0)) { \
                    break; \
                } \
                return prefix##release(me); \
            } \
            case Object_OP_retain: { \
                if (k != ObjectCounts_pack(0, 0, 0, 0)) { \
                    break; \
                } \
                return prefix##retain(me); \
            } \
             \
            case IWait_OP_wait: { \
                if (k != ObjectCounts_pack(1,1,0,0) || \
                    a[0].b.size != 12 || \
                    a[1].b.size != 4) { \
                    break; \
                } \
                 \
                const struct bi { \
                    uint32_t m_msec; \
                    uint32_t m_code; \
                    uint32_t m_events; \
                } *i = (const struct bi*)a[0].b.ptr; \
                uint32_t *result_ptr = (uint32_t*)a[1].b.ptr; \
                int32_t r = prefix##wait(me, i->m_msec, i->m_code, i->m_events, result_ptr); \
                 \
                return r; \
            }  \
            case IWait_OP_signal: { \
                if (k != ObjectCounts_pack(1,0,0,0) || \
                    a[0].b.size != 8) { \
                    break; \
                } \
                 \
                const struct bi { \
                    uint32_t m_code; \
                    uint32_t m_events; \
                } *i = (const struct bi*)a[0].b.ptr; \
                int32_t r = prefix##signal(me, i->m_code, i->m_events); \
                 \
                return r; \
            }  \
        } \
        return Object_ERROR_INVALID; \
    }
