// Copyright (c) 2025, Qualcomm Innovation Center, Inc. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause

#ifndef _MINKCOM_H_
#define _MINKCOM_H_

#include "object.h"

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Get a RootEnv object which can be used to initiate MINK-IPC based
 * communication with QTEE.
 *
 * @param obj The RootEnv object requested by the client.
 * @return Object_OK on success.
 *         Object_ERROR on failure.
 */
int MinkCom_getRootEnvObject(Object *obj);

/**
 * @brief Get a ClientEnv object that is registered with QTEE with client's
 * auto-generated credentials
 *
 * @param root: The RootEnv object for initiating MINK-IPC based communication.
 * @param obj: The ClientEnv object requested by the client.
 *
 * @return Object_OK on success.
 *         Object_ERROR_* on failure.
*/
int MinkCom_getClientEnvObject(Object root, Object *obj);

/**
 * @brief Get a ClientEnv object that is registered with QTEE with client's
 * self-generated credentials
 *
 * @param root: The RootEnv object for initiating MINK-IPC based communication.
 * @param creds: The credentials object self-generated by the client.
 * @param obj: The ClientEnv object requested by the client.
 *
 * @return Object_OK on success.
 *         Object_ERROR_* on failure.
*/
int MinkCom_getClientEnvObjectWithCreds(Object root, Object creds, Object *obj);

/**
 * @brief Get a Memory object representing physically contiguous memory shared
 * with QTEE.
 *
 * @param root: The RootEnv object for initiating MINK-IPC based communication.
 * @param size: Size of the memory represented by the Memory object.
 * @param memObj: The Memory object requested by the client.
 *
 * @return Object_OK on success.
 *         Object_ERROR_* on failure.
*/
int MinkCom_getMemoryObject(Object rootObj, size_t size, Object *memObj);

/**
 * @brief Get the virtual address and size of the memory represented by a
 * Memory object.
 *
 * @param memObj: The Memory object for which information is requested.
 * @param address: Virtual address of the memory represented by the Memory
 *                 object.
 * @param size: Actual size of the memory represented by the Memory object.
 * @return Object_OK on success.
 *         Object_ERROR_* on failure.
*/
int MinkCom_getMemoryObjectInfo(Object memObj, void **address, size_t *size);

#ifdef __cplusplus
}
#endif

#endif // _MINKCOM_H_
