// Copyright (c) 2025, Qualcomm Innovation Center, Inc. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause

/**
 * IAppLegacyTest is an interface that an app can implement to expose the legacy
 * tz_app_cmd_handler interface via SMC Invoke objects
 */
interface IAppLegacyTest {

  /**
   * @brief The object implementing this interface is supposed to redirect the
   * request to the tz_app_cmd_handler in its own application.
   */
  method handleRequest(in buffer request, out buffer response);
};
