// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

/**
* Implements IRegisterTABufCBO which is private and intended only for
* internal use.
*
* @addtogroup CRegisterTABufCBO
* @{
*/
#pragma once
// AUTOGENERATED FILE: DO NOT EDIT

#include <stdint.h>
#include "object.h"

#define CRegisterTABufCBO_UID UINT32_C(268)
