// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

include "IRequestTABuffer.idl"

/**
 * Interface used by HLOS GP Stack to register callback object used in TA auto loading.
 */
 /** @cond */
 interface IRegisterTABufCBO {
 /** @endcond */

  /**
   * @addtogroup IRegisterTABufCBO
   * @{
   */

  /**
    Register a CBO used by HLOS GP Stack to return a memory object filled with
    signed TA elf identified by passed input UUID.

    @param[in] CBO to be registered by QTEE for TA auto loading.

    @return
    Object_OK on success.
  */
  method register (in IRequestTABuffer obj);

  /* @} */ /* end_addtogroup IRegisterTABufCBO */
};
